rm poetry from containers
flywheel-apps/bids-fmriprep pull request #37
Opened 2023-02-06 22:49 UTC by AndysWorth

- Remove poetry inside gear and test container
- Fix bug when running on HPC

2023-04-05 16:53 UTC, dpark6060 requested changes
looks good, but I had some suggestions regarding confusing function names.

2023-04-06 19:37 UTC, AndysWorth commented on README.md
> +This repository will eventually be moved to GitHub and will use Flywheel's best practices for gears.  It is currently in an intermediate state between old development practices and the new ones.  The
Yup.  Good catch.

2023-04-06 19:40 UTC, AndysWorth commented on run.py
>          scratch_dir = run_in_tmp_dir(gtk_context.config["gear-writable-dir"])
That's a good suggestion.  It used to always run in the temp directory.  But Pablo has a new way of doing this and the method will be in the gear-toolkit so this function will go away once we get this repo onto GitLab

2023-04-06 19:42 UTC, AndysWorth commented on pyproject.toml
> +version = "1.4.2+20.2.7"
Yes, exactly.  I have not heard that there is a better way

2023-04-06 20:45 UTC, dpark6060 approved these changes

2023-04-06 20:46 UTC, merged